name: ci

on: [push, pull_request, release]

jobs:
  test:
    name: test setup-wabt on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: clone repo
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
      # - name: install node
      #   uses: actions/setup-node@v1.1.2
      # - name: extract branch name
      #   shell: bash
      #   run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      #   id: extract_branch
      - name: install wabt
        run: node ./main.js
      - name: check a tool
        run: wat2wasm --help
