name: ci

on: [push, pull_request, release]

jobs:
  test:
    name: test setup-wabt on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: clone repo
        uses: actions/checkout@v1.0.0
        with:
          ref: ${{ github.ref }}
      - name: install npm deps
        run: npm install
      - name: install wabt
        run: node ./main.js
      - name: check a tool
        run: wat2wasm --help
